### ISSUE TITLE
Updating for storybook 5

### ISSUE THREAD

**Issue by verticalgrain** [thehashton/killer-storybook-config#20]
Hi, this is very nice! Great initiative to make it easier for folks to set up webpack with storybook. 

Will this be updated to work with storybook V5 in the future?

**Comment by hghazni** [comment]
Hey @verticalgrain sorry for the delay in response, just saw this tonight and I'm in total agreement with you! This needs a v5 upgrade.

The project is now been upgraded to handle Babel `7.11.6` and Storybook v5 plus some other nice upgrades too.

I've tested out full functionality in Storybook and the React App. Everything seems to be working 😉
